import { Download } from 'lucide-react'
import { useState } from 'react'

import { Button } from '@/components/ui/button'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import { downloadRunCsv, downloadRunJson, saveFile } from '@/lib/apiClient'
import { errorMessage } from '@/lib/errors'
import {
  formatCount,
  formatDate,
  formatDecimalUnits,
  formatShortId,
} from '@/lib/formatting'
import type { InventoryResponse, PlanningRunResponse } from '@/lib/types'
import { DerivationDrawer } from './DerivationDrawer'

export function RecommendationTab({
  run,
  inventory,
}: {
  run: PlanningRunResponse
  inventory: InventoryResponse | null
}) {
  const [openLineId, setOpenLineId] = useState<string | null>(null)
  const [downloadError, setDownloadError] = useState<string | null>(null)
  const [downloading, setDownloading] = useState<'csv' | 'json' | null>(null)

  const names = new Map(
    (inventory?.items ?? []).map((item) => [item.item_id, item.item_name]),
  )
  const explanationByLine = new Map(
    run.planning_line_explanations.map((entry) => [entry.planning_line_id, entry]),
  )
  const lineById = new Map(
    run.planning_lines.map((line) => [line.planning_line_id, line]),
  )
  const openLine = openLineId === null ? null : (lineById.get(openLineId) ?? null)

  async function download(kind: 'csv' | 'json') {
    setDownloading(kind)
    setDownloadError(null)
    try {
      // Generated by the API and fetched with the session token — never
      // rebuilt in the browser from the rows on screen.
      const file = await (kind === 'csv'
        ? downloadRunCsv(run.run.run_id)
        : downloadRunJson(run.run.run_id))
      saveFile(file)
    } catch (error) {
      setDownloadError(errorMessage(error))
    } finally {
      setDownloading(null)
    }
  }

  if (run.recommendations.length === 0) {
    return (
      <p className="text-sm text-muted-foreground">
        Nothing needs ordering in this horizon.
      </p>
    )
  }

  return (
    <div className="space-y-3">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <p className="text-sm text-muted-foreground tabular">
          {formatCount(run.recommendations.length, 'proposal')} · run{' '}
          {formatShortId(run.run.run_id)}
        </p>
        <div className="flex gap-2">
          <Button
            variant="outline"
            size="sm"
            disabled={downloading !== null}
            onClick={() => void download('csv')}
          >
            <Download aria-hidden="true" />
            CSV
          </Button>
          <Button
            variant="outline"
            size="sm"
            disabled={downloading !== null}
            onClick={() => void download('json')}
          >
            <Download aria-hidden="true" />
            JSON
          </Button>
        </div>
      </div>

      {downloadError !== null && (
        <p role="alert" className="text-xs text-danger">
          {downloadError}
        </p>
      )}

      <div className="overflow-x-auto rounded-lg border border-border">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Item</TableHead>
              <TableHead>Order on</TableHead>
              <TableHead>Expected</TableHead>
              <TableHead>Supplier</TableHead>
              <TableHead className="text-right">Order units</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {run.recommendations.map((row) => (
              <TableRow key={row.recommendation_id}>
                <TableCell className="font-medium">
                  {/* Focusable control, not a row click handler: the
                      derivation must be reachable by keyboard. */}
                  <button
                    type="button"
                    onClick={() => {
                      setOpenLineId(row.planning_line_id)
                    }}
                    className="-m-1 rounded-md p-1 text-left underline-offset-2 select-none hover:underline focus-visible:ring-2 focus-visible:ring-ring focus-visible:outline-none"
                  >
                    {names.get(row.item_id) ?? row.item_id}
                    <span className="sr-only"> — show how this was calculated</span>
                  </button>
                </TableCell>
                <TableCell className="tabular">
                  {formatDate(row.order_date)}
                </TableCell>
                <TableCell className="tabular">
                  {formatDate(row.expected_delivery_date)}
                </TableCell>
                <TableCell>{row.supplier_id}</TableCell>
                <TableCell className="text-right tabular">
                  {formatDecimalUnits(row.proposed_qty_units)}
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>

      <p className="text-xs text-muted-foreground">
        Proposals for review. Placing an order happens elsewhere.
      </p>

      <DerivationDrawer
        line={openLine}
        exceptions={run.exceptions}
        explanation={
          openLineId === null
            ? null
            : (explanationByLine.get(openLineId) ?? null)
        }
        itemName={
          openLine === null
            ? ''
            : (names.get(openLine.item_id) ?? openLine.item_id)
        }
        onClose={() => {
          setOpenLineId(null)
        }}
      />
    </div>
  )
}
