WITH question_reconciliation(
    number,
    topic,
    assessment,
    clarified,
    remaining,
    project_effect
) AS (
    VALUES
        (1, 'In-transit', 'Partial',
         'Pending Transgourmet orders are downloaded and netted outside the workbook; four KW34 blanks were probably missed.',
         'Export/API, line/status/remaining-qty/receipt fields, partial receipts and cancellations.',
         'Keep dated open-PO netting; source identification is closed, production ingestion is not.'),
        (2, 'Lead times', 'Partial',
         'Current standard ~3 days, fresh ~5 days, future pods ~1 month.',
         'Business/calendar-day semantics, cut-offs, item exceptions and pod go-live.',
         'Remove global 4-week assumption; keep supplier/item config.'),
        (3, 'Shelf life', 'Partial',
         'No explicit current MHD cap for TK/Kuehl/RT; fresh ~3 days; future pods ~1 year.',
         'Sealed/opened meaning, item exceptions and approved hard-cap/max-cover rules.',
         'Use explicit optional policy; do not infer infinite shelf life.'),
        (4, 'S/M/W/Fr', 'Partial',
         'Delivery-day allocations; Penne split/reduced for freezer space and frequent replenishment.',
         'Intended vs placed vs confirmed vs delivered status, units and exact capacity limits.',
         'Separate gross need, dated receipt recommendations and capacity exceptions.'),
        (5, 'Demand/Silo Load', 'Confirmed baseline',
         'Sold-dish forecast/day across three REWE units combined at central prep; two-week consumption plus campaigns and approval.',
         'Daily Phase 1 source/version and stable service-to-planning-location map.',
         'Treat as demand, not capacity; never duplicate the combined value per unit.'),
        (6, 'Stock count', 'Partial',
         'Operators upload manual usable-stock counts to Apicbase and exclude unusable goods.',
         'Exact timestamp, partial/open packs, API fields and legacy 2.5-day reason.',
         'Apicbase is a stock candidate; timestamped canonical contract remains correct.'),
        (7, 'Menu changes', 'Partial',
         'Planner drives menus; Transgourmet orders can be cancelled, pods cannot.',
         'Committed horizon, versioned source, publication and pod last-order rule.',
         'Keep forward-menu coverage and late/non-cancellable PO exceptions.'),
        (8, '20% buffer', 'Partial',
         'Broad assumption covering multiple operational scenarios.',
         'Uniform applicability, override owner and separate yield/safety approval.',
         'Keep 1.20 only in legacy; improved values remain explicit/unapproved.'),
        (9, 'Master data', 'Confirmed examples',
         '5,000 g Creme Fraiche; 250 g current Schnittlauch; Oel equals Sonnenblumenoel; fresh examples; article numbers exist.',
         'Canonical ID precedence, extract, owner/freshness and accepted Excel-to-master migration.',
         'Update fixture expectations; retain stable-ID and source-acceptance gates.'),
        (10, 'Fresh products', 'Confirmed baseline',
         'Sat->Mon, Mon->Tue+Wed, Wed->Thu+Fri, Fri->Sat.',
         'Receipt times, holidays and item exceptions.',
         'Implement actual service-day sums using these baseline windows.'),
        (11, 'Weekly process', 'Partial',
         'Thursday main plan; Monday inventory and sufficiency recheck.',
         'Exact times, urgent path, final decision/order owner and override recording.',
         'Support repeatable re-planning without duplicate PO counting.'),
        (12, 'Other data', 'Inconclusive',
         'Planner says no other data currently available for the listed topics.',
         'Reconcile with the forecast sheet, Apicbase, Transgourmet history and Snowflake candidates.',
         'Do not infer global absence or remove later calibration/source work.'),
        (13, 'Planner experience', 'Partial',
         'Historical stockouts came from unclear delivery models; step-by-step automation is considered viable.',
         'Explicit human-judgement boundary and explanation/override requirements.',
         'Preserve derivations and exceptions; do not add approval/dispatch workflow.')
)
SELECT
    number,
    topic,
    assessment,
    clarified,
    remaining,
    project_effect
FROM question_reconciliation
ORDER BY number;
